Unit object
appleple/acms-google-translate pull request #14
Opened 2024-11-21 11:39 UTC by 1000-x-t30

a-blog cms v3.1.23以降に対応していなかったので修正しました。

2024-11-26 03:47 UTC, uidev1116 requested changes
すみません。不具合もあったので 変更リクエストです。よろしくお願いします！

2024-11-26 03:47 UTC, uidev1116 commented on src/POST/GoogleTranslate/CreateEntry.php
> +            } elseif (is_object($unit)) {
@1000-x-t30 
ここの $unit がオブジェクトであることはないように思えますのでこの部分は削除いただけないでしょうか？
ここの $unit は Engine.php の `buildUnitDate` （タイポしてますね…）で作成されてます！

```php
    /**
     * エントリーユニットのレスポンスデータ組み立て
     *
     * @param int $eid
     * @return array
     */
    protected function buildUnitDate($eid)
    {
        $item = [];
        $units = loadColumn($eid);
        foreach ($units as $unit) {
            $type = detectUnitTypeSpecifier($unit['type']);
            if (!in_array($type, ['text', 'table', 'media', 'image', 'file'], true)) {
                continue;
            }
            $item[] = $unit;
        }
        return $item;
    }
```

2024-11-26 03:47 UTC, uidev1116 commented on src/POST/GoogleTranslate/CreateEntry.php
> +            if (is_array($unit)) {
@1000-x-t30 
ここも $unit がオブジェクトであることはないように思えますのでこの部分は削除いただけないでしょうか？

2024-11-26 03:47 UTC, uidev1116 commented on src/Import.php
> +                            case 'image':
@1000-x-t30 
画像とメディアが適切に複製されないようです…。。
メディアはメディア画像が登録されてない状態で複製され、代替テキストとキャプションも翻訳されないです。
画像はユニット自体消えた状態で複製されました。

2024-11-26 03:47 UTC, uidev1116 commented on src/Import.php
> +                        $current->setId($newId);
@1000-x-t30 
`$current['id']` は `$current->setId` とは異なるということだったかと思いますが、その理屈で行くと、ここも `$current->setTempId` にしないといけないように思えますが、こちらは setIdでも良いのでしょうか？

2024-11-26 09:32 UTC, 1000-x-t30 commented on src/Import.php
> +                        $current->setId($newId);
@uidev1116 
すみません、その通りです。修正しました。

2024-11-26 09:38 UTC, 1000-x-t30 commented on src/Import.php
> +                            case 'image':
@uidev1116 
修正しました。
メディアの代替テキスト/キャプションの保存先とリンクはDBに保存されていないことはわかったのですが、この処理がないとリンクが切れてしまうことはコードを見ても分かりませんでした。
また、お時間ある時に教えていただきたいです。

2024-11-26 09:38 UTC, 1000-x-t30 commented on src/POST/GoogleTranslate/CreateEntry.php
> +            if (is_array($unit)) {
@uidev1116 
その通りです。修正しました。

2024-11-27 01:16 UTC, uidev1116 commented on src/Import.php
> +                            case 'image':
@1000-x-t30 
> 処理がないとリンクが切れてしまうことはコードを見ても分かりませんでした。
また、お時間ある時に教えていただきたいです。

以前の処理だと、メディアユニットの場合に以下の処理が動いてしまい、column_field_1 カラムの値がキャプションで上書きされてしまうことでメディアIDの値が消えてしまい、リンク（画像パス）が切れてしまうということだと思います。

switch 文では、caseに付随する文を空とする場合、次のcaseに付随する文に制御が移行するので、media の場合でも image の処理が動きます。

> caseに付随する文は、空とすることが可能です。 この場合、次のcaseに付随する文に制御が移行します。

<?php
switch ($i) {
    case 0:
    case 1:
    case 2:
        echo "iは3より小さいですが負ではありません";
        break;
    case 3:
        echo "iは3です";
}
?>

[PHP: switch - Manual ](https://www.php.net/manual/ja/control-structures.switch.php#:~:text=case%E3%81%AB%E4%BB%98%E9%9A%8F%E3%81%99%E3%82%8B%E6%96%87%E3%81%AF%E3%80%81%E7%A9%BA%E3%81%A8%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E5%8F%AF%E8%83%BD%E3%81%A7%E3%81%99%E3%80%82%20%E3%81%93%E3%81%AE%E5%A0%B4%E5%90%88%E3%80%81%E6%AC%A1%E3%81%AEcase%E3%81%AB%E4%BB%98%E9%9A%8F%E3%81%99%E3%82%8B%E6%96%87%E3%81%AB%E5%88%B6%E5%BE%A1%E3%81%8C%E7%A7%BB%E8%A1%8C%E3%81%97%E3%81%BE%E3%81%99%E3%80%82)

2024-11-27 02:22 UTC, uidev1116 approved these changes
お疲れ様でした！

2024-11-28 00:15 UTC, atsu666 approved these changes
OKです

2024-11-28 00:15 UTC, merged